# Generated by Django 3.1.1 on 2020-09-14 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiro_url', models.URLField()),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LdaTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTopic', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lezioni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processata', models.BooleanField(auto_created=True, default=False)),
                ('video_url', models.URLField()),
                ('kiro_url', models.URLField(unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.corsi')),
            ],
        ),
        migrations.CreateModel(
            name='WordsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('count', models.IntegerField(db_index=True)),
                ('tf', models.FloatField()),
                ('lezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.lezioni')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=50)),
                ('time_stamp', models.TimeField()),
                ('lezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.lezioni')),
            ],
        ),
        migrations.CreateModel(
            name='LdaWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('ldaTopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ldatopic')),
            ],
        ),
        migrations.AddField(
            model_name='ldatopic',
            name='lezione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.lezioni'),
        ),
        migrations.CreateModel(
            name='BinomiCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binomio', models.CharField(max_length=50)),
                ('count', models.IntegerField(db_index=True)),
                ('tf', models.FloatField()),
                ('lezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.lezioni')),
            ],
        ),
        migrations.CreateModel(
            name='Binomi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=50)),
                ('word2', models.CharField(max_length=50)),
                ('time_stamp', models.TimeField()),
                ('lezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.lezioni')),
            ],
        ),
        migrations.AddIndex(
            model_name='binomi',
            index=models.Index(fields=['word1', 'word2'], name='backend_bin_word1_00dcec_idx'),
        ),
    ]
