# Generated by Django 3.1.1 on 2020-09-05 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processata', models.BooleanField(auto_created=True, default=False)),
                ('kiro_url', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lezioni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processata', models.BooleanField(auto_created=True, default=False)),
                ('video_url', models.CharField(max_length=200, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.corsi')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('time_stamp', models.CharField(max_length=15)),
                ('lezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.lezioni')),
            ],
        ),
        migrations.CreateModel(
            name='Binomi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=50)),
                ('word2', models.CharField(max_length=50)),
                ('time_stamp', models.CharField(max_length=15)),
                ('lezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.lezioni')),
            ],
        ),
    ]
