# Generated by Django 3.1.1 on 2020-09-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corsi',
            name='processata',
        ),
        migrations.AlterField(
            model_name='corsi',
            name='kiro_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='lezioni',
            name='video_url',
            field=models.URLField(unique=True),
        ),
    ]
