# Generated by Django 3.1.1 on 2020-09-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200907_1517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='Words',
        ),
    ]
